Here's my assignment for week one of BrainHack school 2020.

# Create pandas dataframe from .csv file

In [25]:
pwd # locate file for path

'/home/bea/bhs2020/Assignement week1'

In [26]:
#import package
import pandas as pd

In [27]:
#load brainsize.csv file as reading file
csvfile = ('/home/bea/bhs2020/Assignement week1/brainsize.csv')

data = pd.read_csv(csvfile, sep=';', index_col=0)

data.head()

   Gender  FSIQ  VIQ  PIQ Weight Height  MRI_Count
1  Female   133  132  124    118   64.5     816932
2    Male   140  150  124      .   72.5    1001121
3    Male   139  123  150    143   73.3    1038437
4    Male   133  129  128    172   68.8     965353
5  Female   137  132  134    147   65.0     951545

Identify type of data

In [28]:
print('What type is data ? : ',type(data))
print("It stores values in a numpy array:",type(data.values))
data.values[:5]

What type is data ? :  <class 'pandas.core.frame.DataFrame'>
It stores values in a numpy array: <class 'numpy.ndarray'>

array([['Female', 133, 132, 124, '118', '64.5', 816932],
       ['Male', 140, 150, 124, '.', '72.5', 1001121],
       ['Male', 139, 123, 150, '143', '73.3', 1038437],
       ['Male', 133, 129, 128, '172', '68.8', 965353],
       ['Female', 137, 132, 134, '147', '65.0', 951545]], dtype=object)

### Assess for missing values; for this senario, removal of missing values will be adopted

In [40]:
data = pd.read_csv(csvfile, sep=';', na_values=".")
data = data.dropna()

###  Descriptive stats

In [41]:
#results without droppin missing values
print('data.shape: ', data.shape)
print('data.columns: ',data.columns)  # It has columns
print('\nFemale VIQ mean: ', data[data['Gender'] == 'Female']['VIQ'].mean())

data.describe()

data.shape:  (38, 8)
data.columns:  Index(['Unnamed: 0', 'Gender', 'FSIQ', 'VIQ', 'PIQ', 'Weight', 'Height',
       'MRI_Count'],
      dtype='object')

Female VIQ mean:  109.45

,Unnamed: 0,FSIQ,VIQ,PIQ,Weight,Height,MRI_Count
count,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,3.800000e+01
mean,20.973684,113.552632,112.131579,111.342105,151.052632,68.421053,9.067542e+05
std,11.600296,23.815391,22.939605,22.597867,23.478509,3.993790,7.256175e+04
min,1.000000,77.000000,71.000000,72.000000,106.000000,62.000000,7.906190e+05
25%,11.250000,90.250000,90.250000,89.250000,135.250000,66.000000,8.548115e+05
50%,21.000000,116.500000,113.000000,115.000000,146.500000,68.000000,9.053990e+05
75%,30.750000,135.000000,129.000000,128.000000,172.000000,70.375000,9.495405e+05
max,40.000000,144.000000,150.000000,150.000000,192.000000,77.000000,1.079549e+06

### Create and add partY variable with random values

In [42]:
import numpy as np

data['partY'] = np.random.random(size=38)
data

    Unnamed: 0  Gender  FSIQ  VIQ  PIQ  Weight  Height  MRI_Count     partY
0            1  Female   133  132  124   118.0    64.5     816932  0.133722
2            3    Male   139  123  150   143.0    73.3    1038437  0.147753
3            4    Male   133  129  128   172.0    68.8     965353  0.455710
4            5  Female   137  132  134   147.0    65.0     951545  0.823827
5            6  Female    99   90  110   146.0    69.0     928799  0.401696
6            7  Female   138  136  131   138.0    64.5     991305  0.658526
7            8  Female    92   90   98   175.0    66.0     854258  0.383566
8            9    Male    89   93   84   134.0    66.3     904858  0.932260
9           10    Male   133  114  147   172.0    68.8     955466  0.141406
10          11  Female   132  129  124   118.0    64.5     833868  0.866529
11          12    Male   141  150  128   151.0    70.0    1079549  0.493169
12          13    Male   135  129  124   155.0    69.0     924059  0.133076
13          14  Female   140  120  147   155.0    70.5     856472  0.876310
14          15  Female    96  100   90   146.0    66.0     878897  0.112716
15          16  Female    83   71   96   135.0    68.0     865363  0.524253
16          17  Female   132  132  120   127.0    68.5     852244  0.283892
17          18    Male   100   96  102   178.0    73.5     945088  0.181247
18          19  Female   101  112   84   136.0    66.3     808020  0.666699
19          20    Male    80   77   86   180.0    70.0     889083  0.519644
21          22    Male    97  107   84   186.0    76.5     905940  0.289602
22          23  Female   135  129  134   122.0    62.0     790619  0.710769
23          24    Male   139  145  128   132.0    68.0     955003  0.965794
24          25  Female    91   86  102   114.0    63.0     831772  0.004224
25          26    Male   141  145  131   171.0    72.0     935494  0.217795
26          27  Female    85   90   84   140.0    68.0     798612  0.461265
27          28    Male   103   96  110   187.0    77.0    1062462  0.926106
28          29  Female    77   83   72   106.0    63.0     793549  0.404133
29          30  Female   130  126  124   159.0    66.5     866662  0.904474
30          31  Female   133  126  132   127.0    62.5     857782  0.910491
31          32    Male   144  145  137   191.0    67.0     949589  0.456499
32          33    Male   103   96  110   192.0    75.5     997925  0.747858
33          34    Male    90   96   86   181.0    69.0     879987  0.247343
34          35  Female    83   90   81   143.0    66.5     834344  0.762275
35          36  Female   133  129  128   153.0    66.5     948066  0.807594
36          37    Male   140  150  124   144.0    70.5     949395  0.970377
37          38  Female    88   86   94   139.0    64.5     893983  0.789734
38          39    Male    81   90   74   148.0    74.0     930016  0.620781
39          40    Male    89   91   89   179.0    75.5     935863  0.049309

In [43]:
#verify dataframe shape
data.shape

(38, 9)

In [44]:
import numpy as np

data['partY2'] = np.random.random(size=38)
data

,Unnamed: 0,Gender,FSIQ,VIQ,PIQ,Weight,Height,MRI_Count,partY,partY2
0,1,Female,133,132,124,118.0,64.5,816932,0.133722,0.598992
2,3,Male,139,123,150,143.0,73.3,1038437,0.147753,0.258515
3,4,Male,133,129,128,172.0,68.8,965353,0.455710,0.381912
4,5,Female,137,132,134,147.0,65.0,951545,0.823827,0.594980
5,6,Female,99,90,110,146.0,69.0,928799,0.401696,0.254569
6,7,Female,138,136,131,138.0,64.5,991305,0.658526,0.000427
7,8,Female,92,90,98,175.0,66.0,854258,0.383566,0.205608
8,9,Male,89,93,84,134.0,66.3,904858,0.932260,0.376306
9,10,Male,133,114,147,172.0,68.8,955466,0.141406,0.499657
10,11,Female,132,129,124,118.0,64.5,833868,0.866529,0.437229
11,12,Male,141,150,128,151.0,70.0,1079549,0.493169,0.423713
12,13,Male,135,129,124,155.0,69.0,924059,0.133076,0.291602
13,14,Female,140,120,147,155.0,70.5,856472,0.876310,0.675798
14,15,Female,96,100,90,146.0,66.0,878897,0.112716,0.589388
15,16,Female,83,71,96,135.0,68.0,865363,0.524253,0.852577
16,17,Female,132,132,120,127.0,68.5,852244,0.283892,0.005854
17,18,Male,100,96,102,178.0,73.5,945088,0.181247,0.082812
18,19,Female,101,112,84,136.0,66.3,808020,0.666699,0.516861
19,20,Male,80,77,86,180.0,70.0,889083,0.519644,0.272610
21,22,Male,97,107,84,186.0,76.5,905940,0.289602,0.535104
22,23,Female,135,129,134,122.0,62.0,790619,0.710769,0.116678
23,24,Male,139,145,128,132.0,68.0,955003,0.965794,0.813239
24,25,Female,91,86,102,114.0,63.0,831772,0.004224,0.919379
25,26,Male,141,145,131,171.0,72.0,935494,0.217795,0.992275
26,27,Female,85,90,84,140.0,68.0,798612,0.461265,0.241760
27,28,Male,103,96,110,187.0,77.0,1062462,0.926106,0.733796
28,29,Female,77,83,72,106.0,63.0,793549,0.404133,0.050706
29,30,Female,130,126,124,159.0,66.5,866662,0.904474,0.287140
30,31,Female,133,126,132,127.0,62.5,857782,0.910491,0.817916
31,32,Male,144,145,137,191.0,67.0,949589,0.456499,0.458170
32,33,Male,103,96,110,192.0,75.5,997925,0.747858,0.413963
33,34,Male,90,96,86,181.0,69.0,879987,0.247343,0.266773
34,35,Female,83,90,81,143.0,66.5,834344,0.762275,0.141916
35,36,Female,133,129,128,153.0,66.5,948066,0.807594,0.707365
36,37,Male,140,150,124,144.0,70.5,949395,0.970377,0.414447
37,38,Female,88,86,94,139.0,64.5,893983,0.789734,0.467559
38,39,Male,81,90,74,148.0,74.0,930016,0.620781,0.391725
39,40,Male,89,91,89,179.0,75.5,935863,0.049309,0.314711